# Generated by Django 4.2.4 on 2023-08-10 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(verbose_name='Категория мест')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.TextField(verbose_name='Название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.TextField(verbose_name='Название зала')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.TextField(verbose_name='Название фильма')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='movie_images/%Y/%m', verbose_name='Постер')),
                ('date_start', models.DateField(verbose_name='Дата начала проката')),
                ('date_end', models.DateField(verbose_name='Дата окончания проката')),
                ('age_rating', models.TextField(verbose_name='Возрастной рейтинг')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('trailer', models.FileField(upload_to='movie_videos/%Y/%m', verbose_name='Трейлер')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genre', to='cinema_app.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(verbose_name='Ряд')),
                ('seat', models.PositiveIntegerField(verbose_name='Место')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='cinema_app.category')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hall', to='cinema_app.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_session', models.DateField(verbose_name='Дата сеанса')),
                ('time_session', models.TimeField(verbose_name='Время сеанса')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie', to='cinema_app.movie', verbose_name='Фильм')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold', models.BooleanField(default=False)),
                ('order', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='cinema_app.order', verbose_name='Заказ')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session', to='cinema_app.session', verbose_name='Сеанс')),
                ('ticket_seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_seat', to='cinema_app.seat', verbose_name='Место')),
            ],
        ),
    ]
