# Generated by Django 4.2.4 on 2023-08-11 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_name',), 'verbose_name': 'Категория места', 'verbose_name_plural': 'Категории мест'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('genre_name',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ('hall_name',), 'verbose_name': 'Зал', 'verbose_name_plural': 'Залы'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('date_start', 'movie_name'), 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ('hall', 'row', 'seat'), 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('date_session', 'time_session'), 'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sold',
        ),
        migrations.AddField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='session_hall', to='cinema_app.hall', verbose_name='Зал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats_in_hall', to='cinema_app.hall'),
        ),
    ]
