# Generated by Django 4.2.4 on 2023-08-11 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_alter_category_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_hall', to='cinema_app.hall', verbose_name='Зал')),
            ],
        ),
    ]
