# Generated by Django 4.2.4 on 2023-08-11 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0003_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('hall', 'time'), 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('date_session', 'schedule'), 'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='session',
            name='time_session',
        ),
        migrations.AddField(
            model_name='session',
            name='schedule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='session_schedule', to='cinema_app.schedule', verbose_name='Расписание'),
            preserve_default=False,
        ),
    ]
