# Generated by Django 4.2.4 on 2023-08-11 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema_app', '0004_alter_schedule_options_alter_session_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='order',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_of_order',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_hall', to='cinema_app.hall', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='session',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='cinema_app.movie', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='cinema_app.session', verbose_name='Сеанс'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_seat', to='cinema_app.seat', verbose_name='Место'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
