# Generated by Django 4.2.4 on 2023-08-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0005_remove_ticket_order_ticket_date_of_order_ticket_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Заказан'),
        ),
    ]
