# Generated by Django 4.2.4 on 2023-08-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0006_ticket_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_of_order',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
