# Generated by Django 4.2.4 on 2023-08-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0008_remove_ticket_ordered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('id',), 'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
    ]
